### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Sigri44** [ocruzv/desire-oneclick-miner#1]
Hi,

Thx for this app. But what is the level of donation ?
It's not write on the wiki/readme and i haven't found it on the source code !

Thx

**Comment by ocruzv** [comment]
Hello @Sigri44, currently the donation to the oneclick miner (me) is zero and because of that you can donate anything you want to the address on the miner.

Inside it uses KlausT CCMiner, so, dsr-oneclickminer will donate what KlausT CCminer get by default.

**Comment by daodevinc** [comment]
Ok Thx !

Good job, if I manage to run on all my computer I will give you a donation.

You could in the settings, propose an option that will allow to choose the percentage of donate for the software ccminer :)

**Comment by ocruzv** [comment]
Yeah, that sounds good!
